//! `/init` command — project initialization.
//!
//! Detects the project type from marker files, writes a tailored
//! `.kirkforge/config.toml`, and optionally creates a project instructions
//! file (`CLAUDE.md`). Never overwrites existing files without the user
//! opting in.
//!
//! # Detection heuristics (ordered)
//!
//! - `Cargo.toml` → Rust
//! - `package.json` → Node.js
//! - `pyproject.toml` / `setup.py` → Python
//! - `go.mod` → Go
//! - `.git` present → generic git repo
//! - None → generic directory

use std::path::Path;

/// Detected project type with configuration hints.
#[derive(Debug, Clone, PartialEq)]
pub enum ProjectType {
    Rust,
    Node,
    Python,
    Go,
    GenericGit,
    Generic,
}

impl ProjectType {
    fn name(&self) -> &str {
        match self {
            ProjectType::Rust => "Rust",
            ProjectType::Node => "Node.js",
            ProjectType::Python => "Python",
            ProjectType::Go => "Go",
            ProjectType::GenericGit => "git repository",
            ProjectType::Generic => "directory",
        }
    }

    fn allowed_write_dirs(&self) -> Vec<&str> {
        match self {
            ProjectType::Rust => vec!["src/", "tests/"],
            ProjectType::Node => vec!["src/", "lib/"],
            ProjectType::Python => vec!["src/", "tests/"],
            ProjectType::Go => vec!["cmd/", "pkg/", "internal/"],
            ProjectType::GenericGit | ProjectType::Generic => vec![],
        }
    }

    fn deny_paths(&self) -> Vec<&str> {
        match self {
            ProjectType::Rust => vec!["target/"],
            ProjectType::Node => vec!["node_modules/", "dist/", ".next/"],
            ProjectType::Python => vec!["__pycache__/", ".venv/", "*.pyc"],
            ProjectType::Go => vec![],
            ProjectType::GenericGit => vec![".git/"],
            ProjectType::Generic => vec![],
        }
    }
}

/// Detect the project type from the current working directory.
fn detect_project(cwd: &Path) -> ProjectType {
    if cwd.join("Cargo.toml").is_file() {
        return ProjectType::Rust;
    }
    if cwd.join("package.json").is_file() {
        return ProjectType::Node;
    }
    if cwd.join("pyproject.toml").is_file() || cwd.join("setup.py").is_file() {
        return ProjectType::Python;
    }
    if cwd.join("go.mod").is_file() {
        return ProjectType::Go;
    }
    if cwd.join(".git").is_dir() {
        return ProjectType::GenericGit;
    }
    ProjectType::Generic
}

/// Handle `/init` — detect project type and write `.kirkforge/config.toml`.
///
/// Returns a formatted status message for display in the TUI.
pub fn handle_init_command(args: &str, cwd: &Path) -> String {
    let _force = args.trim() == "--force";

    let project = detect_project(cwd);
    let config_dir = cwd.join(".kirkforge");
    let config_path = config_dir.join("config.toml");

    let mut output = String::new();
    output.push_str(&format!("🔍 Detected project type: {}\n", project.name()));

    // --- write config ---
    if config_path.exists() && !_force {
        output.push_str(&format!(
            "⚠ .kirkforge/config.toml already exists at {}\n\
             Use `/init --force` to overwrite, or edit it manually.",
            config_path.display()
        ));
        return output;
    }

    let config_content = generate_config(&project);

    if let Err(e) = std::fs::create_dir_all(&config_dir) {
        output.push_str(&format!("❌ Failed to create .kirkforge/ directory: {}\n", e));
        return output;
    }

    match std::fs::write(&config_path, &config_content) {
        Ok(_) => {
            output.push_str(&format!(
                "✅ Created {}\n",
                config_path.display()
            ));
        }
        Err(e) => {
            output.push_str(&format!(
                "❌ Failed to write config: {}\n",
                e
            ));
            return output;
        }
    }

    // --- optionally create CLAUDE.md skeleton ---
    let claude_md = config_dir.join("CLAUDE.md");
    if !claude_md.exists() {
        let instructions = generate_instructions(&project);
        if std::fs::write(&claude_md, instructions).is_ok() {
            output.push_str(&format!(
                "✅ Created {} (project instructions)\n",
                claude_md.display()
            ));
        }
    } else {
        output.push_str("ℹ CLAUDE.md already exists — not overwritten.\n");
    }

    output.push_str("\nNext: start a session with `kirkforge run`\n");
    output
}

/// Generate a `.kirkforge/config.toml` for the detected project type.
fn generate_config(project: &ProjectType) -> String {
    let mut c = String::new();
    c.push_str("# KirkForge project config\n");
    c.push_str("# Generated by /init — edit as needed.\n\n");

    // Write dirs
    let write_dirs = project.allowed_write_dirs();
    if !write_dirs.is_empty() {
        c.push_str("allowed_write_dirs = [\n");
        for d in &write_dirs {
            c.push_str(&format!("    \"{}\",\n", d));
        }
        c.push_str("]\n\n");
    }

    // Deny paths
    let deny = project.deny_paths();
    if !deny.is_empty() {
        c.push_str("deny_paths = [\n");
        for d in &deny {
            c.push_str(&format!("    \"{}\",\n", d));
        }
        c.push_str("]\n");
    }

    c
}

/// Generate a CLAUDE.md instructions skeleton.
fn generate_instructions(project: &ProjectType) -> String {
    match project {
        ProjectType::Rust => {
            "# Rust Project\n\n\
             - Build: `cargo build`\n\
             - Test: `cargo test`\n\
             - Check: `cargo check`\n\
             - Format: `cargo fmt`\n\
             - Lint: `cargo clippy`\n\n\
             Edit this file to add project-specific instructions for the AI.\n"
                .to_string()
        }
        ProjectType::Node => {
            "# Node.js Project\n\n\
             - Install: `npm install`\n\
             - Test: `npm test`\n\
             - Build: `npm run build`\n\
             - Lint: `npm run lint`\n\n\
             Edit this file to add project-specific instructions for the AI.\n"
                .to_string()
        }
        ProjectType::Python => {
            "# Python Project\n\n\
             - Test: `pytest` or `python -m pytest`\n\
             - Lint: `ruff check .`\n\
             - Format: `ruff format .`\n\
             - Type check: `mypy .`\n\n\
             Edit this file to add project-specific instructions for the AI.\n"
                .to_string()
        }
        ProjectType::Go => {
            "# Go Project\n\n\
             - Build: `go build ./...`\n\
             - Test: `go test ./...`\n\
             - Format: `go fmt ./...`\n\
             - Lint: `golangci-lint run`\n\n\
             Edit this file to add project-specific instructions for the AI.\n"
                .to_string()
        }
        _ => {
            "# Project Instructions\n\n\
             Edit this file to add project-specific instructions for the AI.\n"
                .to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detect_rust_project() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\nname = \"test\"").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Rust);
    }

    #[test]
    fn test_detect_node_project() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("package.json"), "{}").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Node);
    }

    #[test]
    fn test_detect_python_pyproject() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("pyproject.toml"), "[tool]\n").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Python);
    }

    #[test]
    fn test_detect_python_setup_py() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("setup.py"), "from setuptools import setup\n").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Python);
    }

    #[test]
    fn test_detect_go_project() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("go.mod"), "module example.com/test\n").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Go);
    }

    #[test]
    fn test_detect_git_repo() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::create_dir(tmp.path().join(".git")).unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::GenericGit);
    }

    #[test]
    fn test_detect_empty_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Generic);
    }

    #[test]
    fn test_detect_rust_beats_node() {
        // If both exist, Rust wins (checked first)
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\n").unwrap();
        std::fs::write(tmp.path().join("package.json"), "{}").unwrap();
        let pt = detect_project(tmp.path());
        assert_eq!(pt, ProjectType::Rust);
    }

    #[test]
    fn test_project_name() {
        assert_eq!(ProjectType::Rust.name(), "Rust");
        assert_eq!(ProjectType::Node.name(), "Node.js");
        assert_eq!(ProjectType::Generic.name(), "directory");
    }

    #[test]
    fn test_generate_config_rust() {
        let cfg = generate_config(&ProjectType::Rust);
        assert!(cfg.contains("allowed_write_dirs"));
        assert!(cfg.contains("src/"));
        assert!(cfg.contains("deny_paths"));
        assert!(cfg.contains("target/"));
    }

    #[test]
    fn test_generate_config_generic() {
        let cfg = generate_config(&ProjectType::Generic);
        // Generic has empty dirs — config should still be valid TOML
        assert!(!cfg.is_empty());
        assert!(cfg.contains("KirkForge"));
    }

    #[test]
    fn test_generate_instructions_rust() {
        let instr = generate_instructions(&ProjectType::Rust);
        assert!(instr.contains("cargo build"));
        assert!(instr.contains("cargo test"));
    }

    #[test]
    fn test_handle_init_basic() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\n").unwrap();
        let out = handle_init_command("", tmp.path());
        assert!(out.contains("Rust"), "got: {}", out);
        assert!(out.contains("Created"), "got: {}", out);
        assert!(tmp.path().join(".kirkforge/config.toml").exists());
        assert!(tmp.path().join(".kirkforge/CLAUDE.md").exists());
    }

    #[test]
    fn test_handle_init_existing_config_skips() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\n").unwrap();
        let config_dir = tmp.path().join(".kirkforge");
        std::fs::create_dir_all(&config_dir).unwrap();
        std::fs::write(config_dir.join("config.toml"), "# existing\n").unwrap();
        let out = handle_init_command("", tmp.path());
        assert!(out.contains("already exists"), "got: {}", out);
    }

    #[test]
    fn test_handle_init_force_overwrites() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\n").unwrap();
        let config_dir = tmp.path().join(".kirkforge");
        std::fs::create_dir_all(&config_dir).unwrap();
        std::fs::write(config_dir.join("config.toml"), "# old\n").unwrap();
        let out = handle_init_command("--force", tmp.path());
        assert!(out.contains("Created"), "got: {}", out);
        let new_content = std::fs::read_to_string(config_dir.join("config.toml")).unwrap();
        assert!(!new_content.contains("old"), "should have been overwritten, got: {}", new_content);
    }
}
